recent changes

diff --git a/osx b/osx
--- a/osx
+++ b/osx
@@ -1,4 +1,5 @@
-# vim: set ts=4 sw=4 tw=80 syntax=sh
+#!/usr/bin/env bash
+# vim: set ts=4 sw=4 tw=80 syntax=bash
 set +e
 
 function defaults_write {
@@ -169,7 +170,7 @@ function osx_security {
     sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.webdavfs_load_kext.plist               # WebDAV
     sudo launchctl unload -w /System/Library/LaunchDaemons/org.postfix.master.plist                         # email server
     #sudo launchctl unload -w /System/Library/LaunchAgents/com.apple.RemoteUI.plist                         # Remote Control
-    
+
     # remove setuid and setgid
     sudo chmod ug-s /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/MacOS/ARDAgent      # Apple Remote Desktop
     sudo chmod ug-s /sbin/mount_nfs             # NFS
@@ -248,6 +249,47 @@ osx_mail
 osx_timemachine
 osx_reset
 
+# setup some default filetype application associations
+
+{ cat <<eof
+    cx.c3.theunarchiver:gz
+    cx.c3.theunarchiver:rar
+    cx.c3.theunarchiver:tar
+    cx.c3.theunarchiver:zip
+    org.vim.MacVim:css
+    org.vim.MacVim:js
+    org.vim.MacVim:rst
+    org.vim.MacVim:markdown
+    org.vim.MacVim:md
+    org.vim.MacVim:mdwn
+    org.vim.MacVim:mediawiki
+    org.vim.MacVim:sh
+    org.vim.MacVim:text
+    org.vim.MacVim:txt
+    org.vim.MacVim:xml
+    org.vim.MacVim:py
+    org.vim.MacVim:conf
+    org.vim.MacVim:bash
+    org.vim.MacVim:json
+    org.vim.MacVim:yml
+    org.vim.MacVim:yaml
+    org.vim.MacVim:cfg
+    org.vim.MacVim:ini
+eof
+} | grep . |
+while IFS=$':' read bundle_id extension ; do
+  # Grep to see if Bundle ID exists, sending stdout to /dev/null
+  /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -dump | grep $bundle_id > /dev/null
+  # Save exit status (0=success & 1=failure)
+  status=$?
+  # If exit status failed, notify me & exit; if not, change default app for extension
+  if test $status -eq 1 ; then
+    echo "$bundle_id doesn't exist! Fix the script!"
+  else
+    echo -e "\nChanging $extension so it opens with $bundle_id"
+    duti -s $bundle_id .$extension all
+  fi
+done
 
 # Kill affected applications
 for app in Safari Finder Dock Mail SystemUIServer; do killall "$app" >/dev/null 2>&1; done
